### PR TITLE
New Jekyll site for docs

### PR DESCRIPTION
**Pull request by lachlanjc**
/cc @pletcher

### CODE REVIEW

**Comment by pletcher** [comment]
+1

**Comment by lachlanjc** [comment]
@pletcher You need all this on a `gh-pages` branch. Then do the DNS to point here.

**Comment by pletcher** [comment]
Yep yep, I'll do the branch switching soon -- have been juggling a bunch of stuff.

**Comment by lachlanjc** [comment]
👍

On Wednesday, Mar 4, 2015 at 1:59 PM, Charles Pletcher notifications@github.com, wrote:

Yep yep, I'll do the branch switching soon -- have been juggling a bunch of stuff.

**Pull request merged**
